from enum import Enum

class LocatorStrategy(str, Enum):
    """元素定位策略枚举"""
    ID = "id"
    NAME = "name"
    CLASS_NAME = "class_name"
    TAG_NAME = "tag_name"
    LINK_TEXT = "link_text"
    PARTIAL_LINK_TEXT = "partial_link_text"
    CSS_SELECTOR = "css_selector"
    XPATH = "xpath"
    ACCESSIBILITY_ID = "accessibility_id"
    ANDROID_UIAUTOMATOR = "android_uiautomator"
    IOS_PREDICATE = "ios_predicate"
    IOS_CLASS_CHAIN = "ios_class_chain"

class ElementAction(str, Enum):
    """元素操作类型枚举"""
    CLICK = "click"
    DOUBLE_CLICK = "double_click"
    LONG_PRESS = "long_press"
    SWIPE = "swipe"
    SCROLL = "scroll"
    INPUT = "input"
    CLEAR = "clear"
    SUBMIT = "submit"
    GET_TEXT = "get_text"
    GET_ATTRIBUTE = "get_attribute"
    IS_DISPLAYED = "is_displayed"
    IS_ENABLED = "is_enabled"
    IS_SELECTED = "is_selected"
    WAIT_FOR = "wait_for"
    HIGHLIGHT = "highlight"
    SCREENSHOT = "screenshot" 